name: Build Resume

on: 
    workflow_run:
        workflows: ["Test Resume"]
        types:
            - completed
jobs:
    build:
          name: build resume
          runs-on: Ubuntu-latest
          if: ${{ github.event.workflow_run.conclusion == 'success' }}
          steps:
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 
                
            - name: install latex build dependencies
              run: | 
                sudo apt update
                sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
                pip3 install boto3

            - name: checkout repository
              uses: actions/checkout@v4

            - name: build resume
              run: |
                echo "Building pdf....."
                pdflatex resume.tex

            - name: commit the new resume
              run: | 
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
                git add resume.pdf
                git commit -m "update resume"
                git push origin +HEAD:${{ github.event.workflow_run.head_branch }}

            - name: upload resume
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
              run: |
                import boto3
                from botocore.exceptions import ClientError
                import os
                def upload_file(file_name,bucket_name, object_name=None):
                    if object_name is None:
                        object_name = os.path.basename(file_name)

                    s3_client = boto3.client('s3')
                    extra_args = {
                      'ContentType': 'application/pdf'
                    }
                    try:
                      response = s3_client.upload_file(file_name,bucket_name,object_name,ExtraArgs=extra_args)
                    except ClientError as e:
                        print(e)
                        return False
                    return True

                upload_file('resume.pdf','charan-resume-bucket','charan_resume.pdf')
              shell: python
            
            - name: send mail
              uses: dawidd6/action-send-mail@v5
              with:
                connection_url: ${{ secrets.MAIL_CONNECTION_URL }}
                subject: Resume Build Successful
                to: ${{ secrets.RECEIVER_MAIL_ADDRESS }}
                from: ${{ secrets.MAIL_USERNAME }}
                body: Build job of ${{github.repository}} completed successfully! 
                html_body: "<h1>Resume Build Sucessfull</h1><h2>Time: ${{ github.event.head_commit.timestamp }}</h2><br>Access Resume <a href=${{secrets.RESUME_URL}}>Here</a>"
                attachments: resume.pdf                
